### ISSUE TITLE
Server crashes when unfollowiing

### ISSUE THREAD

**Issue by vinyljackers** [SmileycorpMC/follow-me#7]
When we have a mob follow us in 1.17.1 Forge and u shift+click again to unfollow the whole server crashes.

**Comment by vinyljackers** [comment]
![image](https://user-images.githubusercontent.com/38138011/135750950-f8f8ff02-2cad-4b4d-9e47-1ee5ba449f9b.png)

**Comment by vinyljackers** [comment]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2021/10/03, 13:07
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_6084_()" because "this.f_25513_" is null
	at net.minecraft.world.entity.ai.goal.LookAtPlayerGoal.m_8045_(SourceFile:68) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8045_(SourceFile:27) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25389_(SourceFile:63) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(SourceFile:63) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:685) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2494) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:491) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(SourceFile:127) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:51) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2241) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:303) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:623) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:470) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_143264_(ServerLevel.java:384) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(SourceFile:54) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:818) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:683) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.entity.ai.goal.LookAtPlayerGoal.m_8045_(SourceFile:68) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8045_(SourceFile:27) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25389_(SourceFile:63) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(SourceFile:63) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:685) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2494) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:491) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(SourceFile:127) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:51) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2241) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:303) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:623) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: minecraft:cow (net.minecraft.world.entity.animal.Cow)
	Entity ID: 2911
	Entity Name: Cow
	Entity's Exact location: 495.41, 68.00, -1283.50
	Entity's Block location: World: (495,68,-1284), Section: (at 15,4,12 in 30,4,-81; chunk contains blocks 480,0,-1296 to 495,255,-1281), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Entity's Momentum: 0.02, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:470) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_143264_(ServerLevel.java:384) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(SourceFile:54) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}


-- Affected level --
Details:
	All players: 3 total; [ServerPlayer['Galaxy_Babe'/147, l='ServerLevel[world]', x=865.55, y=57.00, z=-1243.30], ServerPlayer['Vinyljackers'/434, l='ServerLevel[world]', x=493.41, y=68.00, z=-1283.70], ServerPlayer['PlatinumAtlas'/1013, l='ServerLevel[world]', x=490.96, y=63.00, z=-217.64]]
	Chunk stats: 5299
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,64,144), Section: (at 0,0,0 in 12,4,9; chunk contains blocks 192,0,144 to 207,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1048282 game time, 1105706 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 77608 (now: false), thunder time: 119110 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:818) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:683) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%23104!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 16.0.2, Eclipse Foundation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Foundation
	Memory: 3529440504 bytes (3365 MiB) / 6878658560 bytes (6560 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 2,49
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: Microsoft Basic Display Adapter
	Graphics card #0 vendor: (Standard display types) (0x1a03)
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: DriverVersion=10.0.14393.0
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 2,13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384,00
	Memory slot #2 clockSpeed (GHz): 2,13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384,00
	Memory slot #3 clockSpeed (GHz): 2,13
	Memory slot #3 type: DDR4
	Memory slot #4 capacity (MB): 16384,00
	Memory slot #4 clockSpeed (GHz): 2,13
	Memory slot #4 type: DDR4
	Memory slot #5 capacity (MB): 16384,00
	Memory slot #5 clockSpeed (GHz): 2,13
	Memory slot #5 type: DDR4
	Memory slot #6 capacity (MB): 16384,00
	Memory slot #6 clockSpeed (GHz): 2,13
	Memory slot #6 type: DDR4
	Memory slot #7 capacity (MB): 16384,00
	Memory slot #7 clockSpeed (GHz): 2,13
	Memory slot #7 type: DDR4
	Virtual memory max (MB): 156563,41
	Virtual memory used (MB): 108899,39
	Swap memory total (MB): 25600,00
	Swap memory used (MB): 0,00
	JVM Flags: 2 total; -Xms512M -Xmx10240M
	Player Count: 3 / 60; [ServerPlayer['Galaxy_Babe'/147, l='ServerLevel[world]', x=865.55, y=57.00, z=-1243.30], ServerPlayer['Vinyljackers'/434, l='ServerLevel[world]', x=493.41, y=68.00, z=-1283.70], ServerPlayer['PlatinumAtlas'/1013, l='ServerLevel[world]', x=490.96, y=63.00, z=-217.64]]
	Data Packs: vanilla, mod:supermartijn642configlib (incompatible), mod:editenchanting, mod:customfence, mod:craftingautomat (incompatible), mod:bagofyurting (incompatible), mod:treeharvester, mod:jei, mod:crystalblocks (incompatible), mod:floralench (incompatible), mod:doggytalents (incompatible), mod:scannable (incompatible), mod:mcwwindows (incompatible), mod:villagernames, mod:mcwpaintings (incompatible), mod:xaeroworldmap (incompatible), mod:comforts, mod:spawnermod (incompatible), mod:toolleveling (incompatible), mod:guardvillagers (incompatible), mod:mcwdoors (incompatible), mod:packingtape (incompatible), mod:feders_scarecrows (incompatible), mod:forge, mod:signtools, mod:durabilitytooltip, mod:ironchest (incompatible), mod:replantingcrops, mod:glumbis (incompatible), mod:betterpingdisplay (incompatible), mod:betterspawnercontrol, mod:toolbelt (incompatible), mod:silentlib, mod:biomesoplenty, mod:creativecore (incompatible), mod:mcwtrpdoors (incompatible), mod:mcwfences (incompatible), mod:silentgear, mod:supermartijn642corelib (incompatible), mod:packedup (incompatible), mod:simplylight, mod:car (incompatible), mod:paintings (incompatible), mod:easy_villagers (incompatible), mod:blockui, mod:multipiston (incompatible), mod:xaerominimap (incompatible), mod:croptopia (incompatible), mod:collective, mod:ring_of_miner, mod:doubleslabs (incompatible), mod:assorteddecor (incompatible), mod:wirelessredstone, mod:buildersaddition (incompatible), mod:worldedit (incompatible), mod:hunterillager (incompatible), mod:cfm, mod:architectury (incompatible), mod:wands (incompatible), mod:reusable_rockets (incompatible), mod:trashcans, mod:chunkloaders, mod:aquaculture, mod:cosmeticarmorreworked (incompatible), mod:mcwlights (incompatible), mod:additionallanterns, mod:additionalbars, mod:additional_lights (incompatible), mod:absentbydesign (incompatible), mod:earthmobsmod (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:storagenetwork (incompatible), mod:ambientsounds (incompatible), mod:wthit (incompatible), mod:productivebees (incompatible), mod:exlinefurniture, mod:atlaslib (incompatible), mod:followme (incompatible), mod:veinmining
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		supermartijn642configlib-1.0.9-mc1.17.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		DisenchantmentEditTable-1.17.1-1.0.4.jar          |Enchantment Edit Table        |editenchanting                |1.0.4               |DONE      |Manifest: NOSIGNATURE
		customfence-1-17-1.jar                            |Customfence                   |customfence                   |1-17-1              |DONE      |Manifest: NOSIGNATURE
		CraftingAutomat-MC1.17.1-1.2.2.jar                |Crafting Automat              |craftingautomat               |1.2.2               |DONE      |Manifest: NOSIGNATURE
		bagofyurting-1.17.1-2.0.0.0.jar                   |Bag of Yurting                |bagofyurting                  |2.0.0.0             |DONE      |Manifest: NOSIGNATURE
		additionallanterns-1.0.0a-mc1.17.jar              |Additional Lanterns           |additionallanterns            |1.0.0a              |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.17.1-3.2.jar                      |Tree Harvester                |treeharvester                 |3.2                 |DONE      |Manifest: NOSIGNATURE
		jei-1.17.1-8.0.0.16.jar                           |Just Enough Items             |jei                           |8.0.0.16            |DONE      |Manifest: NOSIGNATURE
		crystalblocks-0.1.jar                             |Crystal Blocks                |crystalblocks                 |0.1                 |DONE      |Manifest: NOSIGNATURE
		Floral+Enchantment-1.17.1-1.0.1.jar               |Floral Enchanment             |floralench                    |1.17.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.17.1-2.1.0.0.jar                   |Doggy Talents 2               |doggytalents                  |2.1.0.0             |DONE      |Manifest: NOSIGNATURE
		Scannable-MC1.17.1-Forge-1.7.4+8.jar              |Scannable                     |scannable                     |1.7.4+6             |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.1-mc1.17.1.jar                    |Macaw's Windows               |mcwwindows                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		villagernames_1.17.1-3.3.jar                      |Villager Names                |villagernames                 |3.3                 |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.2-mc1.17.1.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.2               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.17.0_Forge_1.17.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.17.0              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.17.1-5.0.0.1.jar                 |Comforts                      |comforts                      |1.17.1-5.0.0.1      |DONE      |Manifest: NOSIGNATURE
		citadel-1.9.3-1.17.1.jar                          |Citadel                       |citadel                       |1.9.3               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.13.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.13.0              |DONE      |Manifest: NOSIGNATURE
		1.17.1-additionalbars-2.1.0.jar                   |Additional Bars               |additionalbars                |2.1.0               |DONE      |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.17.1-1.5.0.jar             |Simple Storage Network        |storagenetwork                |1.17.1-1.5.0        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		forge-branders-spawnermod-1.17.1-1.8.13.jar       |Enhanced Mob Spawners         |spawnermod                    |1.8.13              |DONE      |Manifest: NOSIGNATURE
		toolleveling-1.17.1-1.2.8.jar                     |Tool Leveling                 |toolleveling                  |1.17.1 - 1.2.8      |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.17.1.1.3.3.jar                   |Guard Villagers               |guardvillagers                |1.3.3               |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.4-mc1.17.1.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.4               |DONE      |Manifest: NOSIGNATURE
		additional_lights-1.17.1-2.1.4.jar                |Additional Lights             |additional_lights             |2.1.4               |DONE      |Manifest: NOSIGNATURE
		PackingTape-1.17.1-0.11.1.jar                     |Packing Tape                  |packingtape                   |0.11.1              |DONE      |Manifest: NOSIGNATURE
		feders_scarecrows-1.1.jar                         |Feder's Scarecrow             |feders_scarecrows             |1.1                 |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.75-universal.jar                |Forge                         |forge                         |37.0.75             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		absentbydesign-1.17.1-1.5.0.jar                   |Absent By Design Mod          |absentbydesign                |1.17.1-1.5.0        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		signtools-forge.1.17.1-1.0.0.jar                  |Sign Tools                    |signtools                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		durabilitytooltip-1.0.0-mc1.17.jar                |durabilitytooltip             |durabilitytooltip             |1.0.0               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.17.1-12.0.2.jar                       |Iron Chests                   |ironchest                     |1.17.1-12.0.2       |DONE      |Manifest: NOSIGNATURE
		replantingcrops_1.17.1-2.4.jar                    |Replanting Crops              |replantingcrops               |2.4                 |DONE      |Manifest: NOSIGNATURE
		glumbis-1.1.1.jar                                 |Glumbis                       |glumbis                       |1.1.1               |DONE      |Manifest: NOSIGNATURE
		BetterPingDisplay-1.17.1-1.0.jar                  |Better Ping Display           |betterpingdisplay             |1.0                 |DONE      |Manifest: NOSIGNATURE
		server-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v4.0.1_mc1.17.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		betterspawnercontrol_1.17.1-1.5.jar               |Better Spawner Control        |betterspawnercontrol          |1.5                 |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.17.1-1.17.3.jar                        |Tool Belt                     |toolbelt                      |1.17.3              |DONE      |Manifest: NOSIGNATURE
		silent-lib-1.17.1-5.0.0.jar                       |Silent Lib                    |silentlib                     |5.0.0               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.17.1-14.0.0.38-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.17.1-14.0.0.38    |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.2_mc1.17.1.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.2-mc1.17.1.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.2               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.0-mc1.17.1.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		silent-gear-1.17.1-2.7.3.jar                      |Silent Gear                   |silentgear                    |2.7.3               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.12-mc1.17.jar          |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.12              |DONE      |Manifest: NOSIGNATURE
		packedup-1.0.24-mc1.17.jar                        |PackedUp                      |packedup                      |1.0.24              |DONE      |Manifest: NOSIGNATURE
		simplylight-1.17.1-1.0.1-build.9.jar              |Simply Light                  |simplylight                   |1.17.1-1.0.1-build.9|DONE      |Manifest: NOSIGNATURE
		wthit-forge-3.9.2.jar                             |wthit                         |wthit                         |3.9.2               |DONE      |Manifest: NOSIGNATURE
		car-1.17.1-1.0.5.jar                              |Ultimate Car Mod              |car                           |1.17.1-1.0.5        |DONE      |Manifest: NOSIGNATURE
		paintings-1.17.1-8.0.0.1.jar                      |Paintings ++                  |paintings                     |1.17.1-8.0.0.1      |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.17.1-1.0.7.jar                   |Easy Villagers                |easy_villagers                |1.17.1-1.0.7        |DONE      |Manifest: NOSIGNATURE
		blockui-1.17.1-0.0.20-ALPHA.jar                   |UI Library Mod                |blockui                       |1.17.1-0.0.20-ALPHA |DONE      |Manifest: NOSIGNATURE
		multi-piston-1.17.1-1.1.1.jar                     |Multi-Piston                  |multipiston                   |1.17.1-1.1.1        |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.16.0_Forge_1.17.1.jar           |Xaero's Minimap               |xaerominimap                  |21.16.0             |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.17-FORGE-1.6.1.jar                    |Croptopia                     |croptopia                     |1.6.1               |DONE      |Manifest: NOSIGNATURE
		collective-1.17.1-2.60.jar                        |Collective                    |collective                    |2.60                |DONE      |Manifest: NOSIGNATURE
		RingOfMiner-Forge-1.17.1-1.3.2.jar                |Ring of Miner                 |ring_of_miner                 |1.3.2               |DONE      |Manifest: NOSIGNATURE
		EarthMobs-1.17.1-0.3.1.jar                        |Earth Mobs Mod                |earthmobsmod                  |1.17.1-0.3.1        |DONE      |Manifest: NOSIGNATURE
		DoubleSlabs-1.17-4.0.0.jar                        |Double Slabs                  |doubleslabs                   |4.0.0               |DONE      |Manifest: NOSIGNATURE
		assorteddecor-1.17.1-3.0.1.jar                    |Assorted Decor                |assorteddecor                 |1.17.1-3.0.1        |DONE      |Manifest: NOSIGNATURE
		WirelessRedstone-1.17.1-1.0.0-beta-3.jar          |Wireless Redstone             |wirelessredstone              |1.0.0-beta-3        |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.17.1-20210823a.jar             |Builders Crafts & Addition    |buildersaddition              |1.17.1-20210823a    |DONE      |Manifest: NOSIGNATURE
		Atlas-Lib-1.17.1-1.1.3.jar                        |Atlas Lib                     |atlaslib                      |1.1.3               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.6.jar                           |WorldEdit                     |worldedit                     |7.2.6+4b2d1e7       |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.17.1-2.2.0.jar                    |Hunter Illager                |hunterillager                 |1.17.1-2.2.0        |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre25-1.17.1.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre25         |DONE      |Manifest: NOSIGNATURE
		architectury-2.5.27-forge.jar                     |Architectury                  |architectury                  |2.5.27              |DONE      |Manifest: NOSIGNATURE
		BuildingWands-2.2.5_mc1.17.1-forge.jar            |Building Wands                |wands                         |2.2.5_mc1.17.1      |DONE      |Manifest: NOSIGNATURE
		productivebees-1.17.1-0.7.0.8.jar                 |Productive Bees               |productivebees                |1.17.1-0.7.0.8      |DONE      |Manifest: NOSIGNATURE
		reusable_rockets-1.17.1-1.0.1.jar                 |Reusable Rockets              |reusable_rockets              |1.17.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		trashcans-1.0.10a-mc1.17.jar                      |Trash Cans                    |trashcans                     |1.0.10a             |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.1.7a-mc1.17.jar                    |Chunk Loaders                 |chunkloaders                  |1.1.7a              |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.17.1-2.2.2.jar                      |Aquaculture 2                 |aquaculture                   |1.17.1-2.2.2        |DONE      |Manifest: NOSIGNATURE
		Follow-Me-1.17.1-1.1.7a.jar                       |Follow Me                     |followme                      |1.1.7a              |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.17.1-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.17.1-v1           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		veinmining-forge-1.17.1-0.12.jar                  |Vein Mining                   |veinmining                    |1.17.1-0.12         |DONE      |Manifest: NOSIGNATURE
		exlinefurniture-1.17.1-2.0.jar                    |Exline Furniture              |exlinefurniture               |1.17.1-2.0          |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.0-mc1.17.1.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 930860db-dc89-42b2-aa3b-b93de2870f70
	FML: 37.0
	Forge: net.minecraftforge:37.0.75

**Comment by SmileycorpMC** [comment]
Which mod version are you using?

**Comment by vinyljackers** [comment]
Follow-Me-1.17.1-1.1.7a

**Comment by SmileycorpMC** [comment]
should be fixed as of version 1.17.1-1.1.7b
