### ISSUE TITLE
Crash. Can't join to world

### ISSUE THREAD

**Issue by Kasia1403** [SmileycorpMC/follow-me#8]
[18:21:02] [Client thread/ERROR] [Follow Me]: Failed to sync config entity  from server null
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: java.lang.ClassNotFoundException: 
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at java.lang.Class.forName0(Native Method)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at java.lang.Class.forName(Unknown Source)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.smileycorp.followme.common.ConfigHandler.syncClient(ConfigHandler.java:126)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.smileycorp.followme.common.network.PacketHandler$ConfigSyncHandler.lambda$onMessage$0(PacketHandler.java:44)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.minecraft.util.Util.func_181617_a(Util.java:529)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:21:02] [Client thread/INFO] [STDERR]: [net.smileycorp.followme.common.FollowMe:logError:48]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SmileycorpMC** [comment]
Which version, and what does your config look like?
Also could you send the full crash report or log?

**Comment by Kasia1403** [comment]
MC version 1.12.2 mod version 1.1.5a

**Comment by SmileycorpMC** [comment]
And your config and full crash report?

**Comment by Kasia1403** [comment]
followme.cfg

# Configuration file

general {
    # (Serverside) Entities that follow the player after sneak right-clicked. (uses either classname e.g. EntityZombie or registry name e.g. minecraft:zombie)
    S:entityWhitelist <
    minecraft:villager
    mca:villagermca 
>
}

followme-client.cfg

# Configuration file

general {
    # The name of the text formatting colour to use for following text.
    S:followMessageColour=aqua

    # Use the entities team colour for the follow message?
    B:followMessageUseTeamColour=true

    # How to show an entity is following the player (0: no rendering, 1 message below nameplate
    I:followRenderMode=1
}

But crash report I don't know - I think I deleted it, because I thought it will be not needed.

**Comment by SmileycorpMC** [comment]
If you just play up until the point where it crashes, it should generate another one.
